apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mental-health-api-ingress
  namespace: mental-health
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mental-health.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mental-health-api-service
                port:
                  number: 80